### ISSUE TITLE
Nobody Checks the Issues

### ISSUE THREAD

**Issue by IanWold** [EpxStudio/CollegeLifeSim#1]
It's rather concerning that nobody checks the issues tabs. What do you all think? Will close after 5 comments.

**Comment by deHekus** [comment]
Have there been issues to looks at? None show up for me.

**Comment by josephLeiferman** [comment]
There has been a hundred haven't you seen?

**Comment by IanWold** [comment]
There haven't been any, but I'm super happy to learn now that people check this. WTF @josephLeiferman

**Comment by deHekus** [comment]
I mean, Git Hub hates me si I wouldn't be surprised if it didn't show them to me.

**Comment by IanWold** [comment]
Knowing people check these makes me feel like I can close this issue
